// Generated by gencpp from file talker_listener/replyServ.msg
// DO NOT EDIT!


#ifndef TALKER_LISTENER_MESSAGE_REPLYSERV_H
#define TALKER_LISTENER_MESSAGE_REPLYSERV_H

#include <ros/service_traits.h>


#include <talker_listener/replyServRequest.h>
#include <talker_listener/replyServResponse.h>


namespace talker_listener
{

struct replyServ
{

typedef replyServRequest Request;
typedef replyServResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct replyServ
} // namespace talker_listener


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::talker_listener::replyServ > {
  static const char* value()
  {
    return "73bbf8063d124b838da0a702ede341b0";
  }

  static const char* value(const ::talker_listener::replyServ&) { return value(); }
};

template<>
struct DataType< ::talker_listener::replyServ > {
  static const char* value()
  {
    return "talker_listener/replyServ";
  }

  static const char* value(const ::talker_listener::replyServ&) { return value(); }
};


// service_traits::MD5Sum< ::talker_listener::replyServRequest> should match 
// service_traits::MD5Sum< ::talker_listener::replyServ > 
template<>
struct MD5Sum< ::talker_listener::replyServRequest>
{
  static const char* value()
  {
    return MD5Sum< ::talker_listener::replyServ >::value();
  }
  static const char* value(const ::talker_listener::replyServRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::talker_listener::replyServRequest> should match 
// service_traits::DataType< ::talker_listener::replyServ > 
template<>
struct DataType< ::talker_listener::replyServRequest>
{
  static const char* value()
  {
    return DataType< ::talker_listener::replyServ >::value();
  }
  static const char* value(const ::talker_listener::replyServRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::talker_listener::replyServResponse> should match 
// service_traits::MD5Sum< ::talker_listener::replyServ > 
template<>
struct MD5Sum< ::talker_listener::replyServResponse>
{
  static const char* value()
  {
    return MD5Sum< ::talker_listener::replyServ >::value();
  }
  static const char* value(const ::talker_listener::replyServResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::talker_listener::replyServResponse> should match 
// service_traits::DataType< ::talker_listener::replyServ > 
template<>
struct DataType< ::talker_listener::replyServResponse>
{
  static const char* value()
  {
    return DataType< ::talker_listener::replyServ >::value();
  }
  static const char* value(const ::talker_listener::replyServResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TALKER_LISTENER_MESSAGE_REPLYSERV_H
