// Generated by gencpp from file talker_listener/message.msg
// DO NOT EDIT!


#ifndef TALKER_LISTENER_MESSAGE_MESSAGE_H
#define TALKER_LISTENER_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talker_listener
{
template <class ContainerAllocator>
struct message_
{
  typedef message_<ContainerAllocator> Type;

  message_()
    : num(0)
    , text()  {
    }
  message_(const ContainerAllocator& _alloc)
    : num(0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::talker_listener::message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talker_listener::message_<ContainerAllocator> const> ConstPtr;

}; // struct message_

typedef ::talker_listener::message_<std::allocator<void> > message;

typedef boost::shared_ptr< ::talker_listener::message > messagePtr;
typedef boost::shared_ptr< ::talker_listener::message const> messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talker_listener::message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talker_listener::message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace talker_listener

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'talker_listener': ['/home/william/catkin_ws/src/talker_listener/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::talker_listener::message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talker_listener::message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talker_listener::message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talker_listener::message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talker_listener::message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talker_listener::message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talker_listener::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0947094fac2afc61bd2294d13ec702ed";
  }

  static const char* value(const ::talker_listener::message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0947094fac2afc61ULL;
  static const uint64_t static_value2 = 0xbd2294d13ec702edULL;
};

template<class ContainerAllocator>
struct DataType< ::talker_listener::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talker_listener/message";
  }

  static const char* value(const ::talker_listener::message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talker_listener::message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n\
string text\n\
";
  }

  static const char* value(const ::talker_listener::message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talker_listener::message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talker_listener::message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talker_listener::message_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALKER_LISTENER_MESSAGE_MESSAGE_H
